use_frameworks!

target 'AJModuleServiceSwift_Example' do
  
  pod 'AJModuleServiceSwift',
  :path => '../'

#  pod 'AJKitSwift',
#  :subspecs => ['Foundation', 'UIKit'],
#  :path => '../../AJKitSwift'
  
end
